### ISSUE TITLE
Add `book` entry next to `docs` entry in the navbar

### ISSUE THREAD

**Issue by Luni-4** [burn-rs/burn-rs.github.io#11]
Adding `books` entry immediately next to `docs` entry in the navbar facilitates its visualization

**Comment by antimora** [comment]
Also it'd be great if we provide a link back to github repo for book editing like rust book (see top right icon): https://doc.rust-lang.org/book/ch01-02-hello-world.html

**Comment by nathanielsimard** [comment]
@Luni-4  I've replace the Docs link with the Book link. Since the navbar isn't really mobile friendly yet, I can't have both. The documentation is less important on the website for now.

**Comment by Luni-4** [comment]
@nathanielsimard Thanks a lot! Perhaps we might insert `docs` link in the book for now, so anyone can see the published crates
