### ISSUE TITLE
The Tutorial in the Burn-book is confusing due to some structs used that are not mentioned.

### ISSUE THREAD

**Issue by exo-cortex** [burn-rs/burn-rs.github.io#15]
While going through the example in the burn-book on the `burn.dev`-website I noticed that on around the 3rd page a few items used are not mentioned. The structs in the burn-framework are quite a lot and it's difficult to guess (when someone's new and doing the tutorial) where a module comes from. The first 2 pages mention exactly which module has to be added in the `use::burn::{ ... }, but later it is lacking. Where are those MNIST-items coming from?

This tutorial could be ameliorated by making sure that for every new item used in a code-block its import is also mentioned - or better: at the top of every page all new needed imports are in its own code-block.

Also: Could the burn-framework have changed so that the tutorial is not correct anymore?

**Comment by exo-cortex** [comment]
Oh I realized that some of the imports where actually modules that I had to write myself, but had a typo in them - Oof!

I still get an error though when using `metric_train_numeric()` or `metric_valid_numeric()`. The compiler suggests that there's `metric_train` and `metric_valid` instead.

**Comment by nathanielsimard** [comment]
@exo-cortex Methods `metric_train_numeric` and `metric_valid_numeric` exist, but you have to use burn v0.10.0 and above!
